### PR TITLE
indexable metadata is a subset of optional metadata.

### PR DESCRIPTION
**Pull request by meetgrinder**
they are not mutually exclusive and we do not want the column duplicated in the table

### CODE REVIEW

**Comment by EronWright** [comment]
The new logic is hard to read, at least to me.  Also we should write it in a backwards compatible way, since previous versions of ECS did return a mutually-exclusive set.   If the logic is already backwards compatible, my apologies for being unable to see that.    Allow me to propose an alternate syntax, in a few minutes.

**Comment by EronWright** [comment]
How about:
```
      // optionally define fields for the sys metadata.
      // note that optionalAttributes is a superset of indexableKeys in ECS 2.2.1+, a disjoint set in 2.2.
      (if(withSystemMetadata) {
        val indexables = sysKeys.getIndexableKeys.map(_.getName).toSet
        sysKeys.getIndexableKeys.filterNot(_.getName == ObjectName).map(_.toStructField(sysmd, indexable = true)) ++
          sysKeys.getOptionalAttributes.filterNot(key => indexables.contains(key.getName)).map(_.toStructField(sysmd, indexable = false))
      } else Nil) ++
```

Which is backwards compatible and (IMO) easier to read.   We simply filter out the indexables from the optional attributes.    ObjectName is assumed to be an indexable.

**Comment by meetgrinder** [comment]
Looks reasonable to me. I'll give it a test and repost the PR.

**Comment by EronWright** [comment]
@meetgrinder ping me when this is ready for another review.

**Comment by meetgrinder** [comment]
I've updated the pr and tested.
screen shot 2016-07-20 at 12 29 30 pm

**Pull request merged**
